#!/usr/bin/env bash
# display information about subdomains
domain=$1
tab=( "www" "lb-01" "web-01" "web-02" )

if [ $# -eq 2 ] ; then
    subdomain=$2
    echo -n "The subdomain $2"
    dig $2.$1 | grep -A1 'ANSWER SECTION:' | tail -n 1 | awk '{print " is a " $4 " record and points to " $5}'
else
    for i in "${tab[@]}" ; do
	echo -n "The subdomain $i"
	dig $i.$1 | grep -A1 'ANSWER SECTION:' | tail -n 1 | awk '{print " is a "$4 " record and points to " $5}'
    done
fi