#!/usr/bin/env bash
# Installs Nginx with the following configurations:

sudo apt-get update -y && sudo apt-get upgrade -y
sudo apt-get install -y nginx
sudo chown -R "$USER":"$USER" /var/www/
sudo chown -R "$USER":"$USER" /etc/nginx


touch /var/www/html/index.html
echo "Holberton School" > /var/www/html/index.html
touch /var/www/html/custom_404.html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    root   /var/www/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 http://cuberule.com/;
    }
    error_page 404 /custom_404.html;
    location = /custom_404.html {
		internal;
	}

}" > /etc/nginx/sites-available/default

service nginx restart