#!/bin/bash
cat <<EOT >> eniac
.SH NAME
eniac \- the first electronic general-purpose digital computer. 
.SH SYNOPSIS
eniac
.SH DESCRIPTION
Eniac was Turing-complete, and able to solve "a large class of numerical problems" through reprogramming.
.SH OPTIONS
eniac does not take any options.
.SH SEE ALSO 
.SH BUGS
No known bugs.
.SH AUTHOR
University of Pennsylvania.
EOT
man ./eniac
