#!/usr/bin/env bash
# This script configures an Ubuntu server with localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8
cp /etc/hosts ~/hosts.new
sed -i 's/127.*$/127.0.0.2 localhost/' ~/hosts.new
sed -i '$a\8.8.8.8 facebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts