#!/usr/bin/env bash
# Run Apache on the holbertonschool/265-0 Docker container.
sudo apt-get install apache2 -y
sudo service apache2 start
echo "Hello Holberton" > /var/www/html/index.html
echo "ServerName localhost" >> /etc/apache2/apache2.conf
